services:
    anime_db.item_folder_filler.filler_folder:
        class: AnimeDb\Bundle\ItemFolderFillerBundle\Service\FillerFolder
        arguments: [ @templating ]
        tags:
            -  { name: anime_db.item }